#!/usr/bin/env node

require('babel-register')
require('babel-polyfill')
require('dotenv').config()

if (process.argv.length === 2) {
  console.log('Options:')
  console.log('  --help  Show help')
}

require('yargs')
  .usage('$0 <cmd> [args]')
  // .option('name', {
  //   alias: 'n',
  //   describe: 'provide yer name!'
  // })
  .command('db:seed', 'Run seeds', {}, function (argv) {
    require('./db/seeds')
  })
  .help('help')
  .argv
